version: "3"

services:
    nginx:
        image: nginx
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8081:80"
        depends_on:
            - app
        container_name: nginx

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        depends_on:
            - database
        container_name: app



    database:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_HOSTS=%
            - MYSQL_DATABASE=website
            - MYSQL_ALLOW_EMPTY_PASSWORD=1

        volumes:
            - ./docker/volume_mysql:/var/lib/mysql

        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        user: "mysql:mysql" # Set the user and group to match MySQL inside the container
        container_name: db



